sillsdev/transcriber

- src/components/Transcriber.tsx
- src/context/TranscriberContext.tsx
- src/control/Duration.tsx
* use ceil function so media duration is always greater than current
> TT-1897 set media id for offline only

- src/crud/loadData.ts
- src/hoc/ErrorBoundary.tsx
carry on to logout if resetRequests gets an error
> cleanup archived memberships that come down in linked relationships

- src/components/ScriptureTable.tsx
> wait for remoteId to be populated before remote save

- src/components/Transcriber.tsx
- src/crud/useVProjectUpdate.ts
use projtype on activitystate update
> update project type on project settings

- src/components/App/AppHead.tsx
- src/routes/Access.tsx
> TT-2035 electron remote deprecated

- src/components/MediaTab.tsx
> TT-2063 Auto load occasional

- src/components/AssignSection.tsx
- src/components/RoleIcons.tsx
- allow reset
- fix nested button error report
> TT-2052 Show Assignment

- src/components/PassageRecord.tsx
- src/components/WSAudioPlayer.tsx
check mediaid for correct existing file
> fix the slider position again

- src/components/Team/TeamDialog.tsx
- src/crud/index.ts
- src/crud/useTeamApiRead.ts
- src/crud/useTeamCreate.ts
- read slug before edit
- get slug after create
> TT-2048 Team Edit

- src/components/MediaTab.tsx
Associating with a single item
> TT-2058 associating one item

- src/components/Team/AddCard.tsx
> TT-2074 Solution closing

- src/components/WSAudioPlayer.tsx
Love the self documenting also
> Add ids to wsAudioControl

- src/crud/useMediaRecorder.tsx
- make sure only one audio player requested
> TT-2102 check audio permissions

- src/components/WSAudioPlayer.tsx
- src/crud/useWaveSurfer.tsx
update duration when editing
use overwriteRef in hotkey functions
> keep track of progress and duration in state so they update display

- src/components/UserAvatar.tsx
- src/crud/fontChoice.ts
- src/crud/useTeamApiPull.ts
- src/utils/loadBlob.ts
fix local blob fetch
only pull team if online
> TT-2113 font and avatar local safe url-schema.

- src/components/PlanActions.tsx
- src/components/PlanSheet.tsx
- src/components/ScriptureTable.tsx
just disable deleteicon instead of disappearing
save after delete if resequenced
use localSave if < 10 rows changed
> TT-2269 wait for delete to complete before allowing continue

- src/components/Team/TeamDialog.tsx
- src/hoc/DataChanges.tsx
TT-2293 notice if we've logged out in datachanges
> only repull org when user opens org settings

- src/Sources.tsx
- src/components/AudioTab/AudioTab.tsx
- src/components/AudioTab/getMedia.ts
- src/components/PassageHistory.tsx
- src/components/TranscriptionTab.tsx
- src/control/LastEdit.tsx
- src/routes/Loading.tsx
- src/routes/Profile.tsx
- src/store/orbit/actions.tsx
- src/utils/dateOrTime.ts
- src/utils/index.ts
> TT-2019 localize dates

- src/components/ImportTab.tsx
- src/components/TaskTable.tsx
- src/components/Team/ProjectCard.tsx
- src/components/Team/ProjectMenu.tsx
- src/control/ProjButtons.tsx
Offline should always be allowed to import ptf (not from task table)
> TT-2352 Online Desktop should act like online web

- src/components/Integration.tsx
- src/control/ProjButtons.tsx
- src/store/paratext/reducers.tsx
reset status after complete or error
> getCount on project or passage change

- src/components/TaskHead.tsx
- src/components/TaskItem.tsx
- src/components/TaskTable.tsx
- src/crud/useFlatAdd.ts
Remove section and passage for flat items
Simplify message to just have section and passage
default flat passage number to 1
> TT-2439 Make task list narrow

- src/components/ScriptureTable.tsx
* when deleting allow save without waiting for remote update.
> TT-2446 Allow save on delete without waiting

- .gitignore
- README.md
- amplify/silid/amplify-meta.json
- amplify/silid/parameters.json
- env-config/changeEnv.js
- public/auth-service.js
- src/auth/Auth.tsx
- src/auth/auth0-variables.tsx
> move audience to config files

- src/components/Integration.tsx
- src/utils/localSync.ts
handle non-text, non-notes correctly
> fix the local count status

- src/components/App/AppHead.tsx
- src/utils/axios.tsx
> don't send auth info for userversion - prevent creation of new user

- src/Sources.tsx
- src/components/ScriptureTable.tsx
don't wait for update of plan so delete buttons reenable faster
> TT-2469 remove section update after passage update

- src/schema.tsx
- src/utils/cleanFileName.ts
add single quote to filename restrictions because s3 hates them
> add new index for orbitjs

- src/components/Team/AddCard.tsx
- src/routes/Access.tsx
- src/routes/Welcome.tsx
fix some wording
handle quick transcribe
> move the import button into the without an internet connection paper

- src/components/Transcriber.tsx
> remove resize ability from textarea

- src/routes/Welcome.tsx
- turn off busy
- select online users working offline
> TT-2727-after-import

- src/App.tsx
- src/components/AlertDialog.tsx
- src/components/AssignSection.tsx
- src/components/AssignmentTable.tsx
- src/components/AudioTab/AudioTab.tsx
- src/components/Busy.tsx
- src/components/GroupSettings/GroupSettingsStyles.tsx
- src/components/ImportTab.tsx
- src/components/InvitationTable.tsx
- src/components/PlanSheet.tsx
- src/components/PlanTabs.tsx
- src/components/ScriptureTable.tsx
- src/components/ShapingTable.tsx
- src/components/TaskTable.tsx
- src/components/Team/ProjectDialog/ProjectDialog.tsx
- src/components/TranscriptionShow.tsx
- src/components/TranscriptionTab.tsx
- src/components/UserTable.tsx
- src/control/ChoiceHead.tsx
- src/control/sectionDescription.tsx
- src/routes/EmailUnverified.tsx
- src/routes/Loading.tsx
- src/routes/Logout.tsx
- src/routes/Profile.tsx
- rename createMuiTheme to createTheme
- remove mixins
> mui-warn-fixes

- src/components/WSAudioPlayer.tsx
- src/crud/useMediaRecorder.tsx
- src/crud/useWaveSurfer.tsx
- src/crud/useWavesurferRegions.tsx
remove most console.logs from wavesurfer
> TT-2533 only send new audio if done processing last send

- src/components/TaskTable.tsx
- src/components/Team/ProjectMenu.tsx
- src/components/Transcriber.tsx
- src/components/WSAudioPlayer.tsx
- player interferes with integration,etc
> TT-2455 Stop player on  Project menu

- package.json
- public/auth-process.js
- public/auth-service.js
- public/ipcMethods.js
- src/App.tsx
- src/auth/Auth.tsx
- src/hoc/TokenCheck.tsx
- src/index.tsx
- src/routes/Access.tsx
- src/routes/Logout.tsx
- src/routes/Profile.tsx
- uses latest auth0 react method
- removes need for implicit auth
- adds need for auth code and refresh
- remove /callback endpoint
- optionally enable code rotation
> TT-2775 display sign up first time

- src/App.tsx
- src/auth/Auth.tsx
- src/hoc/TokenCheck.tsx
- src/model/index.tsx
- src/model/token.ts
- src/routes/Access.tsx
- src/routes/EmailUnverified.tsx
- src/routes/Loading.tsx
- check for verified and then load data
> TT-2802 Handle verified email

- public/ipcMethods.js
- src/components/App/AppHead.tsx
- src/hoc/TokenCheck.tsx
- src/routes/Logout.tsx
- src/utils/forceLogin.ts
- src/utils/index.ts
- src/utils/logErrorService.ts
- src/utils/useLogout.ts
- use Electron refresh when necessary
- calculate using en locale
- navigate correctly after each choice
> TT-2819 Token Expire logic

- src/components/AudioTab/AudioTab.tsx
Enables associate to work 2nd time
> TT-2554 reset selected table row on cancel

- src/components/ScriptureTable.tsx
- Fixes TT-2793 that removed state update after save
> TT-2862 Update table state values after save

- src/components/ScriptureTable.tsx
- also fixes TT-2870 trying to add audio when flat not showing
> TT-2867 Show flat faster

- src/components/ScriptureTable.tsx
- make sure we always have the latest copy of rowInfo
> TT-2871 sequence delete, save and update

- src/components/Integration.tsx
also shortname might be undefined
> TT-2829 unable to reproduce, but put in checks for valid project

- src/control/UserList.tsx
- src/control/UserListItem.tsx
- src/routes/Access.tsx
- src/routes/Welcome.tsx
> remove teamlist

- src/__tests__/getWorkflow.ts
- src/__tests__/workflowSheet.ts
- src/crud/getWorkflow.ts
- src/model/workflow.tsx
- src/schema.tsx
- src/utils/index.ts
- src/utils/workflowSheet.ts
> TT-2466b compute workflow sheet

- src/components/Workflow/ScriptureTable.tsx
- refactor save check logic into a method
> TT-2902 Save before record

- src/components/Workflow/ScriptureTable.tsx
- src/components/Workflow/wfResequence.ts
- handle deleing last item
- handle deleting continuous
- no delete or add while save
- resequence ignores deleted
> TT-2901 Deleting unsaved

- src/components/Workflow/ScriptureTable.tsx
- also defaults book to last book
> TT-2907 Add Section after delete

- src/components/WSAudioPlayer.tsx
- src/components/WSAudioPlayerSegment.tsx
- src/components/WSAudioPlayerZoom.tsx
- src/crud/useWaveSurfer.tsx
- src/crud/useWavesurferRegions.tsx
TT-2790 add busy around auto segment
use containerRef in wsPctWidth
> TT-2885 Use HotKeys similar to Audacity

- src/components/AudioDownload.tsx
- src/components/MediaPlayer.tsx
- src/context/TranscriberContext.tsx
- src/crud/fontChoice.ts
- src/crud/useFetchMediaUrl.ts
- also give more detailed media missing error
> TT-2872 auth isn't null when offline but accessToken is

- src/components/Transcriber.tsx
> TT-2049 Set max size for audio resizer

- src/components/TaskTable.tsx
- src/components/Transcriber.tsx
- src/context/TranscriberContext.tsx
- src/crud/useFetchMediaUrl.ts
- src/global.d.ts
- src/index.tsx
move trackedTask to global
use busyRef in setDimensions
> add state to useEffect in case index doesn't change

- src/components/Transcriber.tsx
- src/context/TranscriberContext.tsx
- src/crud/useFetchMediaUrl.ts
- src/crud/useWaveSurfer.tsx
- src/hoc/DataChanges.tsx
reset audioblob when switching tasks
replace wavesurfer's loadBlob because it errors when user clicks around
> fix duration update to account for local paths

- src/store/importexport/electronExport.tsx
- prevents memory containing null ref to plan
> TT-2832 Pull media on export

- src/Sources.tsx
- src/hoc/ErrorBoundary.tsx
> TT-2828b no racing

- src/components/UserTable.tsx
- src/crud/user.ts
- src/routes/Profile.tsx
move user delete to user RemoveUserFromOrg to be consistent
> TT-2985 unassign when removing user from org or deleting user

- src/components/AudioTab/AudioTable.tsx
- src/components/Team/ProjectDialog/ProjectExpansion.tsx
> TT-3005-2 Only show Ready to share in AudioTable if project shared

- src/components/PassageDetail/PassageDetailStepComplete.tsx
- src/components/PassageDetail/WorkflowSteps.tsx
- src/components/Workflow/getWorkflow.ts
- src/context/PassageDetailContext.tsx
> TT-3014 change wfIndex to psgCompletedIndex

- src/components/WSAudioPlayer.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/crud/useWaveSurfer.tsx
only capture before buffer on stop and start recording, not on every buffer push
> TT-3007 handle empty recording

- src/components/WSAudioPlayer.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/crud/useWaveSurfer.tsx
Reverts sillsdev/transcriber#484
> Revert "TT-3007 handle empty recording"

- src/control/SelectRole.tsx
- src/crud/useArtifactCategory.ts
- src/crud/useArtifactType.ts
- src/crud/useMediaResCreate.ts
- src/crud/useOfflineSetup.ts
- src/crud/useOrgWorkflowSteps.tsx
- src/utils/localizeRole.ts
- filter table contents by whether we are offline only
- update default roles
- update tool information
> TT-3058 avoid duplicates from online and offline

- src/components/Discussions/CommentCard.tsx
- src/components/Discussions/CommentEditor.tsx
- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/DiscussionList.tsx
- src/components/PassageDetail/Internalization/SelectResource.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/Workflow/SelectArtifactCategory.tsx
- src/context/PassageDetailContext.tsx
- src/routes/PassageDetail.tsx
TT-3031 resize discussions better
category not required in discussion (can't find the issue)
> TT-3033 don't save empty comments

- src/index.tsx
- src/model/role.tsx
try to wait for database migration
> add PeerReviewer to editor role for testing

- src/__tests__/getWorkflow.test.ts
- src/components/AudioTab/AudioTable.tsx
- src/components/Workflow/ScriptureTable.tsx
disable ready to share until associated with a passage
> TT-3036 initialize mediaShared on new passage

- src/components/Discussions/DiscussionCard.tsx
- src/components/Workflow/SelectArtifactCategory.tsx
- src/crud/useArtifactCategory.ts
wait for remoteId before checking matching offline status
> TT-3060 wait for remoteid, only allow category add for admins

- src/crud/useArtifactCategory.ts
- src/hoc/DataChanges.tsx
for electron, do each project separately
> Split datachanges into 2 calls

- src/routes/Loading.tsx
MUST ADD users:read to the Paratext-Transcriber scope on auth0
> Check Paratext for the invite's email

- src/components/Workflow/PlanActionMenu.tsx
- they are primarily oriented towards collaboration and
don't make sense for a single user project
> TT-3066 Don't allow detail screens for offline only

- src/components/PassageDetail/PassageDetailStepComplete.tsx
- src/context/PassageDetailContext.tsx
auto advance to next step when marked complete
> TT-3128 don't attempt to move past last step

- src/components/Discussions/CommentCard.tsx
- should not display confirmation for delete
> TT-3137 exiting comment more

- src/components/PassageDetail/Internalization/SelectResource.tsx
- src/components/PassageDetail/Internalization/resourceRows.ts
- src/components/Workflow/SelectArtifactCategory.tsx
- fix material ui warnings on resources
> TT-3103b fix test for complete

- src/components/AudioTab/AudioTab.tsx
- src/components/Discussions/CommentCard.tsx
- src/components/Discussions/CommentEditor.tsx
- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/ReplyCard.tsx
- src/components/Discussions/useRecordComment.ts
- src/components/PassageDetail/Internalization/resourceRows.ts
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/context/PassageDetailContext.tsx
- src/crud/media.ts
- src/crud/useArtifactType.ts
- src/crud/useMediaAttach.ts
- attach comment to passage
- attach artifactType
- play without interrupting vernacular
- allow editing comment
> TT-3045 Recording comments

- src/components/Discussions/DiscussionCard.tsx
- put file name in tool tip
- put category as chip on comment count line
> TT-3180 handle title wrap

- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/DiscussionList.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/WSAudioPlayer.tsx
- src/context/PassageDetailContext.tsx
- segment boundaries inserted in subject
- if segment boundaries present, allow user to play it.
> TT-3180 show selected segment

- src/components/ImportTab.tsx
- src/components/ProjectDownload.tsx
- src/store/importexport/actions.tsx
handle error on one project of multiple project download
> unexpected error handler passed in to export functions

- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/UserTable.tsx
- src/routes/Loading.tsx
- also fixes navigation to profile if profile deleted
> TT-3127 navigate to detail

- src/components/Discussions/DiscussionCard.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/context/PassageDetailContext.tsx
- issue number was wrong
- selecting a segment caused player to crash
- segment range was erased from topic
> Tt 3180 discussion ux subject segments

- src/routes/Loading.tsx
fixes TT-1513 fix on Firefox...
> TT-3250 check for projectId as null

- src/components/Discussions/CategoryList.tsx
- src/components/Discussions/DiscussionCard.tsx
> TT-3109 reset discussion fields on add

- src/components/Team/PersonalItem.tsx
- src/components/Workflow/PlanActionMenu.tsx
- src/components/Workflow/PlanAudioActions.tsx
- src/components/Workflow/PlanSheet.tsx
- move detail button to left side.
> TT-3256, TT-3257 Handle offline EditWorkflow cases

- src/components/Discussions/CategoryList.tsx
- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/DiscussionList.tsx
- src/components/GroupSettings/Involvement.tsx
- src/components/GroupSettings/PersonItems.tsx
- src/components/GroupSettings/Team.tsx
- src/components/Integration.tsx
- src/components/PassageDetail/Internalization/getResources.ts
- src/components/PassageDetail/Internalization/resourceRows.ts
- src/components/PassageHistory.tsx
- src/components/Team/ProjectDialog/ProjectType.tsx
- src/components/Team/TeamDialog.tsx
- src/components/UserTable.tsx
- src/components/Visualize.tsx
- src/context/TeamContext.tsx
- src/context/TranscriberContext.tsx
- src/control/SelectRole.tsx
- src/control/SelectUser.tsx
- src/control/UserList.tsx
- src/crud/setDefaultProj.ts
- src/utils/localSync.ts
> TT-3274 make sure vernacular is first

- src/components/Discussions/DiscussionCard.tsx
- src/components/MediaPlayer.tsx
- src/context/PassageDetailContext.tsx
- src/hoc/DataChanges.tsx
catch src missing error on mediaplayer
avoid console errors on discussion selects
> TT-3130 itf upload created files now so remove CheckUploadLocal

- src/context/PassageDetailContext.tsx
- src/mods/react-orbitjs/components/withData.js
- workflowstep and orgworkflowstep in Contenxt
> TT-3096 Fix table loading

- src/components/Discussions/DiscussionCard.tsx
- src/components/PassageDetail/Internalization/resourceRows.ts
- fixes bugs that removed the start and end numbers from new discussions
- only call tool changed the first time a change is made to the subject line.
> TT-3274 sorting audio

- src/components/Discussions/DiscussionCard.tsx
- step uses stage control
- reference displays what it can
> TT-3230 width of ref info on hard

- src/components/WSAudioPlayer.tsx
- src/crud/useWaveSurfer.tsx
Start at beginning if at end when start to play
> TT-3295 Jump to end after a record

- src/components/Discussions/CommentEditor.tsx
- src/components/Discussions/ReplyCard.tsx
- only allow text or audio per comment to reduce confusion
> TT-3292 Reset comment

- src/components/DeleteExpansion.tsx
- src/components/Team/TeamDialog.tsx
- src/context/HotKeyContext.tsx
- src/crud/user.ts
- src/routes/Profile.tsx
This doesn't actually prevent the error, so not sure it's worth merging, although it can't hurt and does show what has been tried.
> TT-2999x  try waiting for all requests before proceeding.

- src/context/HotKeyContext.tsx
TT-3310 use ref for hotkeys instead of state variable
> TT-3305 use splice correctly

- src/components/TranscriptionShow.tsx
- src/components/TranscriptionTab.tsx
- src/crud/index.ts
- src/crud/useTranscription.ts
- also show transcription in dialog based on choice.
> TT-3381b Transcription in dialog

- src/components/Workflow/ScriptureTable.tsx
wait for workflow to be refreshed after save before getting row info
> TT-3391 TT-3392 TT-3383 Save callbacks need a ref for workflow

- src/components/WSAudioPlayer.tsx
- src/crud/useWaveSurfer.tsx
if deleteRegion is deleting all then clear
> TT-3159 setReady to false when recording is deleted

- src/components/ProjectDownloadAlert.tsx
- src/crud/useProjectExport.ts
- src/store/paratext/actions.tsx
- src/utils/dataPath.ts
analyzed uses of getMediaInPlans and fixed some
> TT-3279 handle local filenames better

- src/components/Transcriber.tsx
- src/context/UnsavedContext.tsx
- src/routes/TeamScreen.tsx
add a clear in the team screen for Michael Pelley's testcases
> TT-3388 use a ref for the changedflag inside unsavedcontext

- package.json
- src/components/TaskHead.tsx
> TT-3189 fix assign editor menuitem

- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/WSAudioPlayer.tsx
- src/crud/useWaveSurfer.tsx
TT-???? locate will work second time if user changes segment in between
> TT-3317 notice looping status when setting segments

- src/App.tsx
- src/components/AboutDialog.tsx
- refactor for no nested components
- simplify linking
> TT-2945 external links

- src/components/Team/AddCard.tsx
- src/context/TeamContext.tsx
TT-3581 do not reset values when hiding dialog
> TT-3313 use Refs for callbacks

- src/components/Transcriber.tsx
> TT-3591 No Paratext Pull

- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/DiscussionList.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/WSAudioPlayer.tsx
- src/context/PassageDetailContext.tsx
- src/crud/useWaveSurfer.tsx
- src/crud/useWavesurferRegions.tsx
> TT-3862 handle clicking same marker or same locate segment

- src/crud/getMediaInPlans.ts
- src/crud/getStepComplete.ts
handle no passage in getStepComplete
> TT-3897 remove passage filter from getMediaInPlans

- src/components/MediaPlayer.tsx
- src/components/PassageDetail/Internalization/PassageDetailArtifacts.tsx
- src/context/PassageDetailContext.tsx
- src/crud/useFetchMediaUrl.ts
- resource player grows to space available
- player is now reset to idle after playing
- request playing is true when media is loaded
> TT-3895 Allow playing resource multiple times

- src/components/PassageDetail/PassageDetailItem.tsx
- for Community
- for Back translation
> TT-3830 Require Vernacular

- src/components/PassageDetail/Internalization/SelectMyResource.tsx
- ordering done at the context level
> TT-3997 Maintain Ordering

- src/components/Transcriber.tsx
- src/selector/activitySelector.ts
- src/selector/index.ts
- resize Transcription tool
- no all done in transcription tool
> TT-4002 Display Transcription State

- src/components/GroupTabs.tsx
- will be added when API can change
> TT-3979a Remove Peer Groups

- src/components/PassageDetail/Internalization/SelectProjectResource.tsx
- show progress
- ignore cancel until complete
> TT-4026b Also remove section resource

- src/store/paratext/actions.tsx
- make sure code doesn't end in dash
> TT-4035 Offline Sync lang code

- src/store/paratext/actions.tsx
- use regular expression instead of trim
> TT-4035b fix removing hyphens

- src/components/PassageDetail/Internalization/SelectSections.tsx
- also handle hierarchical when one passage in a section
> TT-4024 Flat chunking

- src/components/PassageDetail/Internalization/PassageDetailArtifacts.tsx
- src/components/PassageDetail/Internalization/TableRow.tsx
start playing of segments that start at 0
show passage/section tooltip on resources
> TT-4020 handle changing to passage resource correctly

- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/crud/useWavesurferRegions.tsx
- src/hoc/SnackBar.tsx
- src/store/upload/actions.tsx
fix mediafiles save to include source segments, performed by etc.
> TT-4062 load phrase bt segments only on that step

- src/components/PassageDetail/PassageDetailTranscribe.tsx
- src/components/StepEditor/StepEditor.tsx
- src/components/StepEditor/StepItem.tsx
- src/components/StepEditor/TranscribeStepSettings.tsx
- src/components/Transcriber.tsx
- src/components/Workflow/SelectArtifactType.tsx
- src/context/TranscriberContext.tsx
- src/crud/useArtifactType.ts
- src/crud/useStepTool.ts
- src/routes/PassageDetail.tsx
so BT,Retell,QA can be it's own transcribe step
> TT-4047 create settings for Transcribe step on workflow

- src/components/UserAdd.tsx
- src/crud/allUsers.ts
- src/crud/useAddToOrgAndGroup.ts
- src/crud/useTeamCreate.ts
- src/routes/Loading.tsx
make allUsersRec return rec instead of array
> TT-4072 filter invitations by my remoteId manually

- src/context/TeamContext.tsx
- src/crud/user.ts
- src/hoc/DataChanges.tsx
- src/routes/Loading.tsx
also notice invitations coming in and accept them
> TT-4070 notice if I've been removed from an organization or group

- src/components/Transcriber.tsx
- src/context/TranscriberContext.tsx
- src/crud/useWaveSurfer.tsx
Don't update duration if you don't have a mediafile still
Queue the wavesurfer clear if there is a file loading
reset Transcriber Context selected if no mediafiles
> TT-4083 a plethora of timing issues.

- src/components/PassageDetail/Internalization/resourceRows.ts
- src/components/PassageDetail/PassageChooser.tsx
- src/components/PassageDetail/PassageDetailStepComplete.tsx
- src/components/WSSegmentParameters.tsx
- src/context/TranscriberContext.tsx
Also default sliders to minimum value
> TT-4017 Refresh Transcriber on passage change

- src/crud/fileOrder.ts
- src/crud/index.ts
- src/index.tsx
- src/store/importexport/electronExport.tsx
- User table order when loading from indexedDb
> TT-4162b Load all tables

- src/components/Invite.tsx
- src/crud/fileOrder.ts
add invitation to file list to be loaded.  Alphabetize file list for easier checking.
> TT-4059 Hide resend unless developer

- src/components/UserAdd.tsx
This is not normally visible to the user
> TT-4163e UserAdd

- src/components/Workflow/PlanSheet.tsx
also...exported strings from previous merge?
> TT-4164 fix hang if no sections

- localization/TranscriberAdmin-en-1.2.xliff
- src/components/PassageDetail/PassageDetailItem.tsx
- src/components/Transcriber.tsx
- src/utils/localUserKey.ts
remove the back to workflow button from transcriber
> TT-3403 remove the transcribe option from the detail screen

- src/components/AudioExportMenu.tsx
- src/components/AudioTab/AudioTable.tsx
- src/components/AudioTab/MediaActions2.tsx
- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/DiscussionMenu.tsx
- src/components/PassageDetail/Internalization/PassageDetailArtifacts.tsx
- src/components/PassageDetail/Internalization/ProjectResourceConfigure.tsx
- src/components/PassageDetail/Internalization/SelectSections.tsx
- src/components/Team/ProjectMenu.tsx
- src/components/TranscriptionTab.tsx
- src/selector/selectors.tsx
- fix other errors identified by removing any as component type
> TT-4273 Fix audio export menu position

- src/components/Team/AddCard.tsx
- if created when intellectual property uploaded then update
> TT-4288-update-proj-and-plan

- src/components/MediaRecord.tsx
- it persists if there is an upload error
> TT-3815 Make Loading... not persist

- src/components/AudioTab/AudioTab.tsx
- src/components/Team/AddCard.tsx
- src/components/Workflow/ScriptureTable.tsx
- When recording exists, show speaker name
> TT-4292 Show speaker

- src/components/PassageDetail/PassageChooser.tsx
- src/components/PassageDetail/PassageDetailStepComplete.tsx
- src/components/Workflow/PlanSheet.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/utils/localUserKey.ts
TT-4298 Position sheet to last passage location
> TT-4298-sect-pass-pos

- src/components/PassageDetail/PassageChooser.tsx
- src/components/PassageDetail/PassageDetailStepComplete.tsx
- src/components/Workflow/PlanSheet.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/utils/localUserKey.ts
* TT-4298 Capture last passage
* Return to most recent row
> TT-4298 Return to passage on sheet (#951)

- src/components/MediaUpload.tsx
- src/components/PassageDetail/PassageDetailItem.tsx
- src/components/Uploader.tsx
don't ask for speaker for anything but vernacular uploads
> TT-4304 reset artifactType when slugs change

- src/components/PassageDetail/PassageDetailTranscribe.tsx
- src/components/TaskTable.tsx
- src/components/Team/ProjectMenu.tsx
- src/components/Transcriber.tsx
Go to done state when transcribing community testing artifacts
> TT-4171 Remove project menu items from task table if in passage detail

- src/components/SpeakerName.tsx
- src/crud/useTeamDelete.ts
- Reset rights on new speaker
- Reset rights if speaker changes
- Reset rights if cleared
- Capture input if user tabs out of speaker, if new ask for rights
> TT-4301 Reseting Rights

- src/components/Team/AddCard.tsx
- since the button runs many methods
> TT-4688 Use Ref for adding cards

- src/routes/Logout.tsx
> TT-4687 logout navigates to login

- src/components/PassageDetail/Internalization/ProjectResourceConfigure.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/crud/useWavesurferRegions.tsx
TT-4699 reload table from saved segments
> TT-4700 fix split region side effect of incorrect current region

- src/components/AudioExportMenu.tsx
- src/components/TranscriptionTab.tsx
- src/control/SelectExportType.tsx
- src/control/TabActions.tsx
- src/routes/Profile.tsx
- Profile page
- drop downs on Transcription tab
> TT-4715 Style changes

- src/components/TreeChart.tsx
- set localization var
- use module global classes def
> TT-4726 report generation

- Makefile
- public/app-process.js
- public/generateUUID.js
- public/ipcMethods.js
- public/preload.js
- src/routes/ElectronImport.tsx
- src/store/importexport/actions.tsx
- src/utils/dataPath.ts
- add unsafe-eval to let browser realize its ok to log on
- change to map for zip files to allow multiple files
- fix Linux build
> TT-4815 fix project import

- src/components/Team/AddCard.tsx
Go into setup automatically when configuring project rather than uploading
> TT-4782 indicate we're leaving home on project create.

- public/ipcMethods.js
- public/preload.js
- src/components/Workflow/AudacityManager.tsx
- src/index.tsx
- src/utils/logErrorService.ts
- log file creation is an async process
> TT-4817 create log file

- src/crud/useAddToOrgAndGroup.ts
- use group relationship for group
> TT-4816 Fix user creation

- src/components/Team/ProjectCard.tsx
- src/context/TokenProvider.tsx
- src/hoc/DataChanges.tsx
- src/hoc/PrivateRoute.tsx
- src/routes/Access.tsx
- src/routes/Loading.tsx
- src/utils/useHome.ts
rename function isAuthenticated to distinguish from auth0 isAuthenticated boolean
> TT-4782 fix project card to still use leaveHome

- src/context/TokenProvider.tsx
- src/index.tsx
- src/utils/useHome.ts
- make sure program knows it isn't logged in
> TT-4834 Incognito Refresh

- craco.config.js
- package-lock.json
- package.json
- src/utils/launchAudacity.ts
- opens separate project for each passage even in a section
- fix process error
> TT-4686 Creating audacity files

- src/components/MediaRecord.tsx
- src/components/PassageDetail/PassageDetailItem.tsx
- src/components/PassageDetail/PassageDetailRecord.tsx
- src/components/Uploader.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/crud/useVProjectCreate.ts
- src/utils/passageDefaultFilename.tsx
Always use default name, even if the previous version had a different naming scheme
> Add project slug to all filenames

- src/components/Team/AddCard.tsx
- src/components/Team/ProjectDialog/ProjectDialog.tsx
- src/crud/useOrgDefaults.ts
- track default language info
- auto open created card
> TT-4852 only give start option on personal

- src/components/Workflow/AudacityManager.tsx
- condition passage changes and name changes separately
> TT-4686 Audacity for each passage

- src/components/ProjectDownload.tsx
- src/store/importexport/actions.tsx
fix pct
if export gets stuck, restart it
> TT-4743 Needy mediafiles was happening twice (restarting after finished)

- src/components/Discussions/CommentCard.tsx
- src/components/Discussions/ReplyCard.tsx
- src/components/Discussions/useRecordComment.ts
- src/components/PassageDetail/Keyterms/KeyTermTable.tsx
- src/components/Uploader.tsx
- src/crud/index.ts
- src/crud/pullTableList.ts
- src/crud/remoteId.ts
- src/crud/useMediaUpload.ts
- src/crud/useSaveComment.ts
Now because that's faster the memory keyMap hasn't updated, so wait for that
> Query for new media only after uploads

- src/components/Team/AddCard.tsx
- src/crud/useNewTeamId.ts
clean up personal orgs in attempt to prevent more being created for each user (although I didn't see anything obvious wrong with the original code)
> TT-4675 don't send null org to uploader

- src/crud/fileOrder.ts
- src/hoc/DataChanges.tsx
- src/model/orgKeytermTarget.tsx
- src/store/importexport/electronExport.tsx
> TT-4889 add orgkeyterm and orgkeytermtarget to import/export

- src/components/Team/ProjectCard.tsx
- src/crud/media.ts
use audioUrl to get ext instead of s3file for local cases
> TT-4964 ignore copyproject status if not copying

- src/store/importexport/electronExport.tsx
- src/store/importexport/reducers.tsx
- src/store/importexport/types.tsx
- src/utils/infoMsg.ts
fix infoMsg not to lose error nested objects
> TT-4987 don't overuse changedRecs...added filtered into fileresponse

- src/components/TranscriptionTab.tsx
- src/crud/media.ts
- src/store/importexport/actions.tsx
- src/store/importexport/electronExport.tsx
- src/utils/passageDefaultFilename.tsx
If not ref and not flat, use section number and passage number Begin implementation of allowing user to specify template
> TT-4974 If no ref and flat, use section title or section number

- src/context/PassageDetailContext.tsx
- src/control/OldVernVersion.tsx
- track start time so only current discussion segment shows playing
> TT-3315 Only current old vern select plays

- src/components/TranscriptionTab.tsx
> TT-4861-primary-button-on-export

- src/components/App/AppHead.tsx
- src/components/HelpMenu.tsx
- if update message is showing
> TT-4847 move help menu down

- src/components/Workflow/PlanSheet.tsx
> TT-4864 book display on current row

- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/DiscussionList.tsx
- src/components/PassageDetail/PassageDetailItem.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/TaskItem.tsx
- src/components/TaskTable.tsx
- src/components/Transcriber.tsx
- src/components/WSAudioPlayer.tsx
- src/context/PassageDetailContext.tsx
- src/context/TranscriberContext.tsx
- src/context/useTodo.tsx
- src/crud/useWaveSurfer.tsx
- src/crud/useWavesurferRegions.tsx
- src/global.d.ts
- src/index.tsx
- src/routes/PassageDetail.tsx
Add playerMedia to context now that it is not only vernacular. Handle that everywhere.
Try again to handle playing only the region in mediafiles that have multiple segments
> TT-5012, TT-5013, TT-5008 Loading player

- src/components/PassageDetail/PassageDetailTranscribe.tsx
- src/components/TaskTable.tsx
- remove cell padding
- correct td reference
- use zero width space for hidden columns
> TT-5015-task-table-width

- src/components/Integration.tsx
- src/crud/useOfflineSetup.ts
Use offlineOnly instead of offline where appropriate
> TT-4053 OfflineOnly create integration records up front

- src/components/SpellingTabs.tsx
- make tab bar not scroll
- change background color
> TT-4849 Spelling tabs

- src/components/Discussions/DiscussionList.tsx
- timing of save and adding reset requires we check both
> TT-5067 Adding Discussion Offline

- src/components/MediaRecord.tsx
- src/components/PassageDetail/RecordButtons.tsx
- src/components/PassageRecordDlg.tsx
Give load existing button an icon to match other buttons
> TT-5079 Make Load existing button show up on PassageRecord Dialog

- src/components/Discussions/CommentCard.tsx
- src/components/Discussions/CommentEditor.tsx
- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/DiscussionList.tsx
- src/components/Discussions/ReplyCard.tsx
- src/components/MediaRecord.tsx
- src/components/PassageDetail/Internalization/ProjectResourceConfigure.tsx
- src/components/PassageDetail/Keyterms/TargetWordAdd.tsx
- src/components/PassageDetail/PassageDetailItem.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/PassageDetail/PassageDetailRecord.tsx
- src/components/PassageDetail/WorkflowSteps.tsx
- src/components/Peers/usePeerGroups.tsx
- src/components/ProvideRights.tsx
- src/components/StepEditor/StepEditor.tsx
- src/components/Transcriber.tsx
- src/components/Workflow/PlanSheet.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/context/PassageDetailContext.tsx
- src/context/UnsavedContext.tsx
- src/control/Stage.tsx
- src/control/StageReport.tsx
- src/routes/Profile.tsx
- src/routes/TeamScreen.tsx
Clear tools if request not to save - either from unsavedContext or Discussion filter
> TT-4824 Disable steps if recording

- src/components/MediaUpload.tsx
- src/components/Uploader.tsx
If no files were uploaded successfully, don't pullTableList
> TT-5072 recheck sizes when uploadType changes

- package-lock.json
- package.json
- src/Sources.tsx
- src/components/ErrorFallback.tsx
- src/index.tsx
- src/utils/localUserKey.ts
- src/utils/logErrorService.ts
- src/utils/useCheckOnline.ts
- correctly sets staging and production
- includes user id in report
- begin documenting localStorage keys
> TT-4989 bugsnag update

- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/Transcriber.tsx
TT-5100 compare undefined as empty string
> TT-5070 let transcriber save segments so we don't get a race

- src/components/AudioTab/Template.tsx
- happens when nothing in template and dialog adds content
> TT-5125 Make Template Label smaller

- src/components/PassageDetail/RecordButtons.tsx
- when resized small, display buttons left aligned and overflow chopped
> TT-5114 Record Buttons

- src/components/ProjectDownloadAlert.tsx
- src/crud/useOfflineTeamList.ts
- src/routes/Welcome.tsx
- src/store/importexport/electronExport.tsx
- get offlineAvailable missing
> TT-5128 No launch after update

- src/components/Team/CategoryListEdit.tsx
- src/crud/useArtifactCategory.ts
> TT-5139, TT-5137 Save only if changes

- src/crud/useOfflineSetup.ts
- src/crud/useOrgWorkflowSteps.tsx
- Removes creation of offline duplicate workflow steps
- If steps exist, they need to be hidden manually
> TT-5113 Remove offline duplicate creation

- src/components/Discussions/CommentCard.tsx
- src/components/MediaPlayer.test.tsx
- src/components/MediaPlayer.tsx
- src/components/PassageDetail/Internalization/PassageDetailArtifacts.tsx
- src/components/PassageDetail/TeamCheckReference.tsx
- src/components/Workflow/PlanSheet.tsx
- src/context/PassageDetailContext.tsx
- Provide progress control for segmented Resources
- Also fixes TT-5141, TT-5143, TT-5144, TT-5145
> TT-5058-TT-5141-TT-5145 segmented playback

- src/context/PassageDetailContext.tsx
- after playing old vernacular, reset the start and end
> TT-5232 Reset Old Vern Play

- src/Sources.tsx
- src/crud/updateConsultantWorkflowStep.ts
- src/store/importexport/actions.tsx
- change consultant tool from discuss.
> TT-5237 Migrate workflowsteps and orgworkflowsteps

- src/Sources.tsx
- src/crud/updateConsultantWorkflowStep.ts
- src/store/importexport/actions.tsx
- only do old ones
- do online records online
- do offline records while offline
> TT-5237b Migrating Consultant Check Workflow step

- src/Sources.tsx
- src/components/App/AppHead.tsx
- src/index.tsx
- src/utils/useCheckOnline.ts
- check when starting program
- only report bugs to bugsnag when online
> TT-5123 Handle offline

- migration/2.16.8/PublishingData.sql
- migration/2.16.8/views.sql
- src/components/PassageDetail/PassageDetailChooser.tsx
- src/components/Workflow/PlanActionMenu.tsx
- src/components/Workflow/PlanSheet.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/components/Workflow/useWfLocalSave.ts
- src/components/Workflow/useWfOnlineSave.ts
- src/components/Workflow/wfResequence.ts
- src/control/PlanIcons.tsx
- src/crud/loadData.ts
- src/crud/usePassageType.ts
TT-5289 Add move passage up/down.
> TT-5288 Sequencenums to decimal TT-5289 move passage 

- src/components/AssignmentTable.tsx
- src/components/AudioTab/getMedia.ts
- src/components/AudioTab/getPassages.ts
- src/components/AudioTab/getReference.ts
- src/components/ImportTab.tsx
- src/components/PassageDetail/Internalization/SelectSections.tsx
- src/components/PassageDetail/PassageDetailChooser.tsx
- src/components/TaskItem.tsx
- src/components/TranscriptionTab.tsx
- src/components/Workflow/PlanSheet.tsx
- src/components/Workflow/ScriptureTable.tsx
- src/components/Workflow/getWorkflow.ts
- src/components/Workflow/useWfPaste.tsx
- src/context/TeamContext.tsx
- src/control/RefRender.test.tsx
- src/control/RefRender.tsx
- src/control/SectionPassageTitle.tsx
- src/crud/PassageDescription.tsx
- src/crud/PassageReference.tsx
- src/crud/nextPasId.ts
Remove publishing from flat projects.
Don't count publishing sections in section counts that show
> TT-5296, TT-5281, TT-5312 remove flat publishing

- src/components/PublishExpansion.tsx
> TT-5338b Allow delete after add

- src/components/Sheet/PlanSheet.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/filterMenu.tsx
- src/components/Sheet/usePlanSheetFill.tsx
- handle showing filter properly
- only add graphic column to plans with publishing info
> TT-5346 Edit in right column

- src/components/Sheet/PlanSheet.tsx
- src/components/Sheet/usePlanSheetFill.tsx
> TT-5346 handle flat filling

- src/components/App/AppHead.tsx
- reset project and plan if on team screen
> TT-5349 My Account stay on team screen

- src/components/App/AppHead.tsx
- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/ReplyCard.tsx
- src/components/Integration.tsx
- src/components/PlanTabs.tsx
- src/components/Team/AddCard.tsx
- src/components/Team/PersonalItem.tsx
- src/components/Team/ProjectCard.tsx
- src/components/UserMenu.tsx
- src/context/TeamContext.tsx
- src/control/ProjButtons.tsx
- src/crud/useArtifactCategory.ts
- src/crud/useArtifactType.ts
- src/crud/useNewTeamId.ts
- src/crud/useOfflineSetup.ts
- src/crud/useOrgDefaults.ts
- src/crud/useOrgWorkflowSteps.tsx
- src/crud/useProjectDefaults.ts
- src/crud/useSanityCheck.ts
- src/crud/useTeamCreate.ts
- src/hoc/DataChanges.tsx
- src/hoc/SnackBar.tsx
- src/routes/Access.tsx
- src/routes/ElectronImport.tsx
- src/routes/Welcome.tsx
- src/utils/useCheckOnline.ts
- fix errors when starting and transitioning
- fix duplicate personal team project
> TT-5268 Missing Workflow

- src/components/PassageDetail/PassageDetailChooser.tsx
- src/components/PassageDetail/usePassageNavigate.ts
- first reset view
- then navigate to new passage
- then proceed to first available step
> TT-5357 Fix step complete

- src/components/App/AppHead.tsx
- src/routes/Access.tsx
- src/routes/Welcome.tsx
- the transitions are necessary
we're waiting for actions to complete
> TT-5403 Shorten transitions

- src/components/PassageDetail/PassageDetailTranscribe.tsx
- src/components/ResourceEdit/ResourceOverview.tsx
- src/components/StepEditor/TranscribeStepSettings.tsx
- src/components/Team/AddCard.tsx
- src/components/Transcriber.tsx
- src/control/Language.tsx
- capture direction and font in settings.
- apply them to transcriber control
> TT-5408 Use transcriber step language

- src/components/PassageDetail/Keyterms/KeyTermTable.tsx
- avoid getting hung up on busy
> TT-5275 Saving Term Text

- src/components/PassageDetail/PassageDetailTranscribe.tsx
- src/context/PassageDetailContext.tsx
- src/context/TranscriberContext.tsx
- src/routes/PassageDetail.tsx
> TT-5421b Handle navigation

- src/components/PassageDetail/Keyterms/KeyTermTable.tsx
- src/routes/Profile.tsx
- src/store/importexport/electronExport.tsx
Account for offlineOnly records in orgkeyterm export
> TT-5275 use SaveComplete to turn off the busy flag after a save

- src/components/Integration.tsx
- src/components/PassageDetail/PassageDetailTranscribe.tsx
- src/components/TranscribeReject.tsx
- src/components/Transcriber.tsx
- src/routes/PassageDetail.tsx
- Steps not complete
- use Rejct for verb on button
- Sync also advances to next step
> TT-5432 Handle Reopen & Reject

- src/components/StepEditor/StepEditor.tsx
- second transcriber step is for review
> TT-5436 Customize names with artifact and language

- src/components/PassageDetail/PassageDetailTranscribe.tsx
don't move on reopen...too many times we don't want to do that simplify review check to see if this is the second vernacular step and it's right after the first
> TT-5444, TT-5445 parse the settings before checking artifactid

- src/components/PassageDetail/PassageDetailTranscribe.tsx
- need to move back to transcribe step to see the segments.
- answers question from TT-5444 pull request #1380
> TT-5438 Restore segments on Reopen

- src/index.tsx
- if no deeplink is present, make sure it is removed
> TT-1611 Fix deep link

- src/components/PublishExpansion.tsx
- src/components/Team/TeamDialog.tsx
- src/crud/useBible.ts
- src/schema.tsx
> TT-5456 TT-5458 TT-5459  Remove duplicate bibleid control

- src/components/Sheet/usePlanSheetFill.tsx
- chapter rows are passages so fall back to attached media file.
> TT-5385 Chapter Recording load

- src/components/Sheet/ScriptureTable.tsx
- src/schema.tsx
> TT-5489 graphics validation error

- public/execa/index.d.ts
- public/execa/index.js
- public/execa/lib/command.js
- public/execa/lib/error.js
- public/execa/lib/kill.js
- public/execa/lib/promise.js
- public/execa/lib/stdio.js
- public/execa/lib/stream.js
- public/execa/license
- public/execa/package.json
- public/execa/readme.md
- public/ipcMethods.js
> TT-5502 Launching Audacity

- src/components/PassageDetail/PassageDetailStepComplete.tsx
- src/components/Sheet/useShowIcon.ts
- src/components/TranscriptionTab.tsx
- src/components/TreeGrid.tsx
- src/context/PassageDetailContext.tsx
- TT-4979 step complete available
- TT- 5453 step complete navigation
> TT-5501 TT-4979 TT-5453 Show Transcription

- src/components/Sheet/useShowIcon.ts
- src/crud/useSaveComment.ts
> TT-5494 fix comment save flow to save mediafile before working on discussion

- src/components/ProjectDownload.tsx
- don't cancel until downloaded
- also resolves TT-5423
> TT-5499 Downloading offline content

- src/components/Sheet/ScriptureTable.tsx
TT-5518 don't add chapter if not a good reference
> TT-5282 ignore other books besides the first one

- src/components/Uploader.tsx
> TT-5071 adjust timing so all error messages show

- src/components/ResourceEdit/ResourceTabs.tsx
- src/components/ResourceEdit/SelectNote.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/getSheet.ts
- src/components/Sheet/usePlanSheetFill.tsx
- src/components/Sheet/useShowIcon.ts
- src/crud/index.ts
- src/crud/useGraphicFind.ts
- src/crud/useSharedResCreate.ts
- src/crud/useSharedResUpdate.ts
- src/model/sheet.tsx
- use note category graphic as default
- show color as border
- update reference with category
- put commas between search keywords
> TT-5528 Note Category Graphic and color

- src/components/AudioTab/AudioTable.tsx
- src/components/ResourceEdit/ResourceTabs.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/usePlanSheetFill.tsx
- src/components/Team/CategoryEdit.tsx
- src/components/Team/CategoryListEdit.tsx
- src/components/Team/CategoryTabs.tsx
- src/control/RefRender.test.tsx
- src/control/RefRender.tsx
- src/crud/useGraphicFind.ts
- src/crud/useSharedResCreate.ts
- src/crud/useSharedResUpdate.ts
- src/utils/localSync.ts
- handles category names with spaces
- use memo for Audio User Avatar
- clean up CategoryListEdit name
> TT-5528 Use pipe for ref

- src/components/Sheet/PlanSheet.tsx
- src/components/Sheet/usePlanSheetFill.tsx
- src/control/MediaTitle.tsx
- Allow select and copy of Section - Description cols
> TT-5386 Enable editing sheet titles

- src/components/BookSelect.tsx
- src/components/PassageDataTable.tsx
> TT-5566 Avoid Constant Shaking

- src/components/AssignSection.tsx
- src/components/TreeGrid.tsx
- src/crud/usePassageState.ts
- use same col orders
- align data to headers
> TT-5568 TT-5569 Assignment Table

- src/components/GraphicRights.tsx
- limit graphic rights list to team rights holders
> TT-5509 Team Graphic Rights

- src/components/GraphicRights.tsx
- src/components/Sheet/usePlanSheetFill.tsx
- src/components/Team/CategoryEdit.tsx
- src/components/Team/CategoryListEdit.tsx
- src/crud/useArtifactCategory.ts
- src/crud/useGraphicFind.ts
- src/crud/useSharedResCreate.ts
- src/crud/useSharedResUpdate.ts
- fix handler that sets rights name
- pass in teamId when on Team screen
- check for null values
> TT-5591 fix category rights

- src/components/Sheet/ScriptureTable.tsx
> TT-5321 Retain Section head badge

- src/components/Sheet/PlanSheet.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/filterMenu.tsx
- src/components/Sheet/getSheet.ts
- src/components/Sheet/shtResequence.ts
- clear will reset to min section
> TT-5617 Track Min section

- src/components/HelpMenu.tsx
- src/components/ProjectDownload.tsx
- src/components/ProjectDownloadAlert.tsx
- src/components/Sheet/AudacityManager.tsx
- src/crud/fontChoice.ts
- src/crud/getMediaInPlans.ts
- src/crud/media.ts
- src/crud/useAvatarSource.ts
- src/crud/useFetchMediaUrl.ts
- src/routes/ElectronImport.tsx
- src/store/importexport/electronExport.tsx
- src/store/upload/actions.tsx
- src/utils/dataPath.ts
Fix DataPath so it works for local files
> Fix Download check

- src/Sources.tsx
- src/crud/syncToMemory.ts
- src/crud/useOfflineSetup.ts
- src/crud/useOfflnMediafileCreate.ts
- src/index.tsx
- src/model/mediaFile.tsx
- src/schema.tsx
- src/store/importexport/actions.tsx
- src/utils/localUserKey.ts
Wait for migrations to finish before restoring backup to memory
> TT-5505 Wait for migrations to finish before restoring backup to memory

- src/components/Sheet/PlanActionMenu.tsx
- src/components/Sheet/PlanMoreMenuItems.tsx
- src/components/Sheet/usePlanSheetFill.tsx
- src/utils/localSync.ts
- show in Action column
- Empty if unpublished
- Globe if published
> TT-5377 Move Publish Button

- src/components/Discussions/DiscussionCard.tsx
- src/components/Discussions/DiscussionList.tsx
- when one is resolved or unresolved.
> TT-5655 Refresh Discussions

- src/components/AssignSection.tsx
- src/components/AssignmentTable.tsx
- src/components/TreeGrid.tsx
- only show sections that can be assigned
- no checkbox on passage lines
- refresh when changes are made
> TT-2932 TT-5540 TT-5656 Assignments

- src/components/PassageDetail/PassageDetailRecord.tsx
- src/components/SpeakerName.tsx
> TT-5353 Speaker Name

- src/components/Team/CategoryEdit.tsx
> TT-5521 Customize color picker

- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/getSheet.ts
- when publishing allow for sections greater than one
> TT-5685 Section Greater than 1

- src/components/Sheet/PlanAudioActions.tsx
- src/components/Sheet/PlanSheet.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/crud/usePublishLevel.ts
Finish save or update before changing sheet.
keep scrolled region on screen
adjust height of empty rows
> TT-5720 One update at a time

- src/components/Sheet/usePlanSheetFill.tsx
- turn off publishing doesn't show beta
> TT-5757-only-published-beta

- src/control/UserList.tsx
- src/control/UserListItem.tsx
- src/crud/index.ts
- src/crud/loadData.ts
- src/crud/useOfflineList.ts
- src/routes/Access.tsx
- src/routes/Logout.tsx
- src/routes/Welcome.tsx
- src/store/importexport/actions.tsx
- src/store/importexport/electronExport.tsx
- don't create extra users
- show projects of each offline user
> TT-5642 Import offline project

- src/components/AudioTab/AudioTable.tsx
- src/components/AudioTab/getMedia.tsx
- src/components/Sheet/ScriptureTable.tsx
TT-5774 change version history to version
> TT-5769 show media created date

- src/components/MediaPlayer.tsx
- the issue is still there that with complex .mp3 files (variable encoding) the position may be slightly off sometimes. see comment on issue
> TT-5742 Fix play of configured resources

- src/store/importexport/actions.tsx
- src/store/importexport/electronExport.tsx
don't mess with remoteIds on export
> TT-5778 check for empty recs on import

- src/components/Team/ProjectCard.tsx
- src/components/Team/ProjectDialog/ProjectBook.tsx
- src/components/Team/ProjectDialog/ProjectDialog.tsx
> TT-5782 fix update error

- src/crud/useArtifactType.ts
- if no relationships on artifact record, allow it.
> TT-5681-offline-workflow-settings

- src/components/Sheet/ScriptureTable.tsx
- src/crud/useProjectDefaults.ts
- src/utils/useWaitForRemoteQueue.ts
TT-5721 don't recheck online if we don't care
> TT-5818 grab book from project for general

- src/components/Team/CategoryEdit.tsx
- src/crud/syncToMemory.ts
- src/crud/useGraphicCreate.ts
- src/crud/useGraphicUpdate.ts
sync updated graphic record to memory
> Use resource id to create graphic name

- src/components/Transcriber.tsx
- src/components/TranscriptionShow.tsx
- src/control/WebFontStyles.tsx
- src/crud/fontChoice.ts
> TT-5831-missing-font-selection

- src/utils/localSync.ts
- Cross chapter content is expected to be in the chapter with the larger number of verses
> TT-5056 Pulling cross chapter content

- src/components/PassageDetail/PassageDetailMarkVerses.test.tsx
- src/components/PassageDetail/PassageDetailMarkVerses.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/TranscriptionShow.tsx
- src/context/HotKeyContext.tsx
- src/crud/fontChoice.ts
- src/crud/loadData.ts
- src/crud/useTranscription.ts
- src/crud/useWaveSurfer.tsx
- src/utils/infoMsg.ts
- add rows to end
- don't access missing rows
> TT-5917 TT-5919 Small Verse Table

- src/components/PassageDetail/PassageDetailMarkVerses.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/Transcriber.tsx
- src/components/WSAudioPlayer.tsx
- src/crud/useWaveSurfer.tsx
- src/crud/useWavesurferRegions.tsx
- src/utils/namedSegments.ts
- The Next Segment button (or hot key) inserts verse markup if not present
- initial verse markup inserted if transcription empty
- shift works with arrow keys in transcription
> TT-5923 Insert verse markup in transcription

- src/components/PassageDetail/PassageDetailMarkVerses.test.tsx
- src/components/PassageDetail/PassageDetailMarkVerses.tsx
- don't insert duplicate verse numbers so bridges don't leave extra verses at the bottom
- handle bridges when checking before save
- handle verses with letters when checking
> TT-5922b-no-dup-with-bridge

- src/components/PassageDetail/PassageDetailMarkVerses.test.tsx
- src/components/PassageDetail/PassageDetailMarkVerses.tsx
- verses need recalculation after final verses are loaded.
> TT-5939-cross-chapter-refs

- src/components/MediaPlayer.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/control/MediaTitle.tsx
stop playing if we want a new playitem
MediaTitle set src to new media
> TT-5914 calculate version number for chapter numbers

- src/components/Sheet/AudacityManager.tsx
- src/crud/useFetchMediaUrl.ts
- src/crud/useSanityCheck.ts
- src/hoc/DataChanges.tsx
- src/utils/index.ts
- src/utils/useDataChanges.ts
- src/utils/useDownloadMedia.ts
download file needed for audacity
download any new files created by others
> TT-5894 and TT-4804

- src/components/ResourceEdit/ResRefTable.tsx
- converts cross chapter ref into refs for each chapter
> TT-5856 Cross Chapter Shared Refs

- src/components/LimitedMediaPlayer.test.tsx
- src/components/LimitedMediaPlayer.tsx
- shared resources
- uploaded resources
> TT-5906 Using LimitedPlayer for full file

- public/downloadFile.js
- src/crud/useFetchMediaUrl.ts
- src/crud/useSanityCheck.ts
- src/hoc/DataChanges.tsx
- src/utils/useDataChanges.ts
don't download on sanity check
fetch new url when new mediafile because it has the seturl still
> TT-5960 delete local file if error downloading occurs

- src/components/Transcriber.tsx
- src/utils/namedSegments.test.ts
- src/utils/namedSegments.ts
- handle merging two segment lists for display
>  TT-5948 TT-5950 Verse and Auto Segments 

- src/components/PassageDetail/PassageDetailTranscribe.tsx
- src/components/PassageDetail/usePassageNavigate.ts
- src/context/UnsavedContext.tsx
TT-5809 Next passage flow should go to first passage next step if on last passage
> TT-5796 next passage not working on transcriber submint

- src/components/ResourceEdit/ResourceKeywords.tsx
- src/components/ResourceEdit/ResourceOverview.tsx
- Refactor ResourceKeywords component to handle empty keyword strings
- Refactor ResourceOverview component to simplify code and improve readability
Co-authored-by: Greg Trihus <gtryus@gmail.com>
> TT-5872 fix undefined keyword crash

- src/business/player/usePlayerLogic.ts
- src/components/HiddenPlayer.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
Refactor PassageDetailPlayer component and setCurrentSegment function
Co-authored-by: Greg Trihus <gtryus@gmail.com>
> TT-5954 Keep initial segment in Phrase Back Translation

- src/components/PassageDetail/PassageDetailMarkVerses.tsx
- highlight segment row of current wave form segment.
> TT-6009 Standardize Mark Verse Segments

- package-lock.json
- package.json
- src/components/ArtifactStatus.tsx
- src/components/PassageDetail/ConsultantCheckReview.tsx
- src/components/PassageDetail/PassageDetailTranscribe.tsx
- fix Phrase Back Translate
- fix Whold Back Translate
- improve Consultant Check
- Fix electronjs dependencies for node 16
> TT-6015 Fix crashing tools (r3.2.2 hotfix)

- src/components/PassageDetail/PassageDetailItem.tsx
> TT-6015b No player when audio missing PBT - WBT

- package-lock.json
- package.json
- src/components/PassageDetail/Internalization/PassageDetailArtifacts.tsx
- src/components/PassageDetail/Internalization/SortableItem.tsx
- src/components/PassageDetail/Internalization/SortableList.tsx
- src/components/PassageDetail/Internalization/TableRow.tsx
- src/components/PassageDetail/Internalization/index.ts
- src/components/StepEditor/StepEditor.tsx
- src/components/StepEditor/StepItem.tsx
- src/components/StepEditor/StepList.tsx
- src/components/StepEditor/index.ts
- src/context/PassageDetailContext.tsx
- src/control/DragHandle.tsx
- src/hoc/VertListDnd.test.tsx
- src/hoc/VertListDnd.tsx
- src/utils/useMounted.ts
- updated useMounted to work correctly in development as well as production
- use key to refresh drop target
> TT-3812 replace react-sortable-hoc witn  hello-pangea/dnd

- src/components/AudioTab/AudioTable.tsx
- src/components/Sheet/PlanAudioActions.tsx
- src/components/Sheet/PublishButton.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/getSheet.ts
- src/components/Sheet/usePlanSheetFill.tsx
- src/components/Sheet/useSheetLocalSave.ts
- src/components/Sheet/useSheetOnlineSave.ts
- src/crud/usePublishDestination.ts
- src/model/sheet.tsx
- status is reported using 4 directions, one for each destination.
> TT-6077 Report Publishing Status

- src/components/MediaUpload.tsx
- src/components/PassageDetail/Internalization/PassageDetailArtifacts.tsx
- src/control/LinkEdit.tsx
- disable save for invalid links
> TT-6055 Check for valid links

- src/__tests__/getSheet.test.ts
- src/components/AudioTab/AudioTable.tsx
- src/components/Sheet/PlanAudioActions.tsx
- src/components/Sheet/PlanSheet.tsx
- src/components/Sheet/getSheet.ts
- src/crud/usePublishDestination.ts
- background beta for passages
- only show status when sharing or publishing
> TT-6077b Update publish status

- src/components/AudioTab/AudioTable.tsx
- src/components/ConfirmPublishDialog.tsx
- src/components/ShapingTable.tsx
- src/components/TaskTable.tsx
- src/components/TranscriptionTab.tsx
- also fix ShapingTable key missing error
> TT-6077c Fix AudioTable not load defaults

- src/utils/isVisual.ts
- TT-6070 everything non-audio shows up as visual
> TT-6050 Resource Type Change doesn't forget type

- src/components/MediaUpload.tsx
- src/control/MarkDownEdit.tsx
- src/crud/useOfflnMediafileCreate.ts
- src/store/upload/actions.tsx
- allow user to add
- TT-6061 display text edit as 40%
- allow text dialog to expand to most of screen
> TT-6092 Offline Link and Text and TT-6061 show long text

- localization/TranscriberAdmin-en-1.2.xliff
- src/components/ImportTab.tsx
- src/components/PassageDetail/Internalization/FindAquifer.tsx
- src/components/PassageDetail/Internalization/FindBibleBrain.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/hoc/DataChanges.tsx
- src/utils/useDataChanges.ts
- src/utils/useWaitForRemoteQueue.ts
> make useWaitForRemoteQueue actually wait

- src/components/AudioTab/AudioTab.tsx
- src/components/AudioTab/AudioTable.tsx
- src/components/Sheet/PlanSheet.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/usePlanSheetFill.tsx
- src/context/PlanContext.tsx
don't show publish row in audiotable if publishing is not on
> changed canHidePublising to publishingOn

- src/components/ArtifactStatus.tsx
- src/components/PassageDetail/PassageDetailChooser.tsx
- src/components/PassageDetail/PassageDetailItem.tsx
- src/components/PassageDetail/SelectRecording.tsx
- src/control/StyledBox.tsx
- TT-4046 fix issue with sorting play item
- also fixes TT-6007
> TT-6036 Handle many back translations

- src/components/ResourceEdit/NoteTitle.tsx
- src/components/Sheet/PlanAudioActions.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/usePlanSheetFill.tsx
notice new shared resource records on scripture table
> TT-6158 create shared resource record when publish to internalization

- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/filterMenu.tsx
- reset t undefined on clear
- display number of real sections against number of total real sections
> TT-5634 Filter badge

- src/components/WSAudioPlayer.tsx
- src/store/upload/actions.tsx
- src/utils/axios.tsx
- src/utils/useNoiseRemoval.ts
remove the wavesurfer while waiting
> TT-6156 save requested audio to a temporary s3 file to send to AI

- src/components/ProjectDownload.tsx
- src/components/ProjectDownloadAlert.tsx
- src/components/TranscriptionTab.tsx
- src/crud/useProjectExport.ts
- src/store/importexport/actions.tsx
- if download cancelled reset busy flag and stop downloading
> TT-6159 Allow cancelling download

- src/components/StepEditor/DiscussStepSettings.tsx
- src/components/StepEditor/StepEditor.tsx
- save closes as well
- cancel closes without saving
- close closes when there is nothing to save
> TT-4967, TT-6191 Discuss tool save and cancel buttons

- src/components/WSAudioPlayer.tsx
- src/crud/useWaveSurfer.tsx
- src/utils/loadBlob.ts
- src/utils/useNoiseRemoval.ts
Send and receive larger blobs as s3files
> reset cancel before NR

- src/components/WSAudioPlayer.tsx
- src/utils/useNoiseRemoval.ts
> Remove task from timer as soon as it comes back successfully

- src/components/PassageDetail/PassageDetailMarkVerses.tsx
- src/components/PassageDetail/PassageDetailTranscribe.tsx
- src/context/PassageDetailContext.tsx
- src/index.tsx
- src/utils/useMyNavigate.ts
> use useGetGlobal to check changed

- src/components/ProjectDownloadAlert.tsx
- src/routes/Logout.tsx
- no download dialog w/o download files
- allow Download Later to exit
> TT-6135-6168-6240 handle exit and download better

- src/business/asr/SelectAsrLanguage.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/crud/useGetAsrSettings.ts
- on created projects w/o lang set on transcribe and pbt
> TT-6263 ASR should work in all cases

- src/business/asr/AsrProgress.tsx
- src/components/PassageDetail/Internalization/FindAquifer.tsx
- src/components/PassageDetail/Internalization/FindBibleBrain.tsx
- src/components/PassageDetail/PassageDetailMarkVerses.tsx
- src/components/PassageDetail/PassageDetailPlayer.tsx
- src/components/Transcriber.tsx
- src/crud/useWavesurferRegions.tsx
wrap axiosPost in try or catch
> return multiple tasks if timing available

- src/components/AudioTab/AudioTable.tsx
- src/components/ConfirmPublishDialog.tsx
- src/components/Sheet/PlanSheet.tsx
> TT-6309 check bibleid and bibleName before Yes enabled

- src/components/Sheet/PlanSheet.tsx
- src/control/ProjButtons.tsx
- don't erase verse range on flat sheets
> TT-6307-6150b use multi row selection

- src/components/Sheet/useSheetPaste.tsx
- skip title rows and note rows
> TT-5307 Pasting publishing sheets

- src/components/Peers/usePeerGroups.tsx
- src/crud/related.ts
- src/crud/useAllUserGroup.ts
- src/crud/useOrgDefaults.ts
- src/crud/usePermissions.tsx
- src/crud/useRole.ts
- src/utils/useStepPermission.test.ts
- src/utils/useStepPermission.ts
- add tests for useStepPermission
> TT-6422 Allow record with vernacular permission

- src/components/Sheet/ScriptureTable.tsx
- needs to refresh when org is updated
> TT-6421 Set default filter on new project

- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/getSheet.ts
- Everyone can see title rows if publishing is enabled.
> TT-6428 Title persist without passages

- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/filterMenu.tsx
- Add a close button as primary
- other buttons are alternates
> TT-6448 Default sheet filter as clear

- localization/TranscriberAdmin-en-1.2.xliff
- localization/TranscriberAdmin-en.xlf
- src/components/Sheet/usePlanSheetFill.tsx
- src/store/localization/exported-strings-name.json
- src/store/localization/reducers.tsx
remove and Export from can Publish
> TT-6438 no assign offline

- src/components/AssignSection.tsx
- src/components/AssignmentTable.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/utils/axios.tsx
use axios call to change all sections in one call
> TT-6418 disable while saving

- src/components/PassageDetail/PassageDetailStepComplete.tsx
- src/utils/useStepPermission.ts
- if permission enabled only admin can change multi-step status
> TT-6493 Multistep status

- src/components/PassageDataTable.tsx
- src/components/PassageDetail/Internalization/SelectSharedResource.tsx
- src/components/ResourceEdit/ResourceTabs.tsx
- src/components/ResourceEdit/SelectNote.tsx
- src/components/Sheet/ScriptureTable.tsx
- src/components/Sheet/SelectArtifactCategory.tsx
- src/crud/useSharedResCreate.ts
- src/crud/useSharedResUpdate.ts
Show what reference we're using in note find
sort note list by title
wait to set category selection until the list is there
> TT-6526 Don't lose new links in worksheet save

- README.md
- src/__tests__/FaithbridgeIframe.test.tsx
- src/__tests__/useFaithbridgeResult.test.tsx
- src/components/PassageDetail/Internalization/FaithbridgeIframe.tsx
- src/components/PassageDetail/Internalization/FindAquifer.tsx
- src/components/PassageDetail/Internalization/FindTabs.tsx
- src/components/PassageDetail/Internalization/PassageDetailArtifacts.tsx
- src/components/PassageDetail/Internalization/useFaithbridgeResult.ts
- also add sources to the text
> TT-6604 update to use query as description

- src/components/Team/PersonalItem.tsx
- src/components/Team/ProjectDialog/projectSort.tsx
- src/components/Team/TeamItem.tsx
- src/context/TeamContext.tsx
- TT-6693 only sort if more than one
> TT-6685 Add Personal sort

- src/Sources.tsx
- src/crud/loadData.ts
- src/index.tsx
- load all orbit data at once
- activate coordinator after loading
> TT-6720 improve load time 10 fold
